import java.util.*;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.Key;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
/**
 *
 * @author Alex Ibarra
 */
public class frmEncriptacion extends javax.swing.JFrame {
    File fichero;
    /**
     * Creates new form frmEncriptacion
     */
    public frmEncriptacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRutaEntrada = new javax.swing.JTextField();
        cboOperacion = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFrase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRutaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtRutaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 650, 40));

        cboOperacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Encriptar", "Desencriptar" }));
        cboOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOperacionActionPerformed(evt);
            }
        });
        getContentPane().add(cboOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 250, 50));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ENCRIPTACIÓN O DESENCRIPTACIÓN AES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 40));

        lblFrase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrase.setText("Introduce la frase compartida con el destinatario:");
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ingrese la ruta del archivo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 160, 40));

        btnEjecutar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 160, 40));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 160, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 40, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Selecciona la operación a realizar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtFrase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 510, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\alexi\\Desktop"));
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION){
           fichero = fileChooser.getSelectedFile();
           txtRutaEntrada.setText(fichero.getPath());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        //Ejecucion de encriptación o desencriptación
        String nombre;
        Cipher aes;
        try{
            BufferedReader bf = new BufferedReader(new FileReader(fichero));
            String texto="",linea;
            //Se obtiene el texto del archivo de entrada
            linea=bf.readLine();
            while(linea!=null){
                texto=texto+linea;
                if((linea=bf.readLine())!=null)
                    texto=texto+"\n";
            }
            //Se forma el nombre del archivo a crear, ya sea cifrado o descifrado
            if(cboOperacion.getSelectedIndex()==0)
                nombre=fichero.getAbsolutePath().replace(".txt","")+"_C.txt";
            else
                nombre=fichero.getAbsolutePath().replace(".txt","")+"_D.txt";
            BufferedWriter bw;
            //Se verifica la opción del usuario
            if(cboOperacion.getSelectedIndex()==0){
                //Encriptación
                try{
                    //Se genera una llave a partir de la frase que conocen ambas partes
                    Key key = new SecretKeySpec(txtFrase.getText().getBytes(),  0, 16, "AES");
                    //Se obtiene el algoritmo de cifrado AES
                    aes = Cipher.getInstance("AES/ECB/PKCS5Padding");
                    //Se coloca en modo encriptación
                    aes.init(Cipher.ENCRYPT_MODE, key);
                    //Se encripta la información
                    byte [] textoEncriptado = aes.doFinal(texto.getBytes("UTF-8"));
                    texto=Base64.getEncoder().encodeToString(textoEncriptado);
                    //Se escribe la cadena encriptada en el archivo de salida
                    bw = new BufferedWriter(new FileWriter(nombre));
                    bw.write(texto);
                    bw.close();
                    JOptionPane.showMessageDialog(this, "Encriptación exitosa", "Éxito",1);
                }catch(Exception e){
                    
                }
            }else{
                //Desencriptación
                try{
                    //Se obtiene la llave a partir de la información que ambas partes conocen
                    Key key1 = new SecretKeySpec(txtFrase.getText().getBytes(),  0, 16, "AES");
                    //Se obtiene el algoritmo de cifrado AES
                    aes = Cipher.getInstance("AES/ECB/PKCS5Padding");
                    //Se coloca en modo desencriptación
                    aes.init(Cipher.DECRYPT_MODE, key1);
                    //Se desencripta el texto
                    byte[] textoDesencriptado = aes.doFinal(Base64.getDecoder().decode(texto));
                    //Se convierte a cadena el arreglo de bytes.
                    texto=new String(textoDesencriptado);
                    //Se escribe el texto desencriptado en el archivo de salida
                    bw = new BufferedWriter(new FileWriter(nombre));
                    bw.write(texto);
                    bw.close();
                    JOptionPane.showMessageDialog(this, "Desencriptación exitosa", "Éxito",1);
                }catch(BadPaddingException be){
                    JOptionPane.showMessageDialog(this, "Llave errónea","Error",JOptionPane.ERROR_MESSAGE);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado","Error",JOptionPane.ERROR_MESSAGE);
                }  
            }
        }catch(IOException e){
            e.printStackTrace();
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtRutaEntrada.setText("");
        cboOperacion.setSelectedIndex(0);
        lblFrase.setText("Introduce la frase compartida con el destinatario:");
        txtFrase.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cboOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOperacionActionPerformed
        // TODO add your handling code here:
        if(cboOperacion.getSelectedIndex()==0)
            lblFrase.setText("Introduce la frase compartida con el destinatario:");
        else
            lblFrase.setText("Introduce la frase compartida con el remitente:");
    }//GEN-LAST:event_cboOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEncriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEncriptacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JTextField txtFrase;
    private javax.swing.JTextField txtRutaEntrada;
    // End of variables declaration//GEN-END:variables
}
